### ISSUE TITLE
Consider uploading tar.gz to PyPI

### ISSUE THREAD

**Issue by jlstevens** [pyviz/pyct#30]
There are pros and cons to .zip and .tar.gz but the latter 1) is the default on linux and mac (but not windows) 2) what we have generally been using so far.

Switching to .zip would mean updating all our conda-forge recipes which get the source archive from PyPI. For these reasons, I would considering forcing upload as .tar.gz even if it might make it trickier for windows users who don't have the suitable decompression software.

**Comment by jlstevens** [comment]
Note that I am assuming that using .tar.gz involves updating the fewest conda-forge recipes. If that isn't true, I am find leaving it as .zip by default.

**Comment by ceball** [comment]
I am ok with using tar.gz instead of zip. I think probably only datashader, geoviews, and holoplot currently have zip source distributions on pypi.

(Just mentioning, another option would be to upload both, but I don't particularly like that one. With wheels for installation, and the source on github, I doubt it's important to provide a source distribution on pypi that can be inspected natively in the windows file manager.)

In any case, this is just a change to the default `formats` parameter value; I'll make it for the next pyctdev release.

**Comment by jlstevens** [comment]
Right now the conda-forge recipes I can find that use .tar.gz are ``holoviews``, ``param`` and ``lancet``. We do have other projects with tar.gz files on PyPI that don't have conda-forge recipes yet that could have (e.g ``imagen``). GeoViews and holoplot are new on PyPI/conda-forge so they may be easier to update but I'll leave the final decision up to you.

**Comment by ceball** [comment]
Switched to tar.gz by default in v0.4.7a0
